import {Head} from '@pages/_document';

const MyHead = () => {
  return <Head>
    <title>Sharper Image Code Exam</title>
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
};

export default MyHead;